// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Songster.iOS
{
	public partial class SearchViewController : UIViewController, SearchView, SearchTableDataSourceListener
	{
		private SearchViewModel ViewModel { get; set; }
		private SearchPresenter Presenter { get; set; }

		public SearchViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			ViewModel = new SearchViewModel ();
			Presenter = new SearchPresenter (this, ViewModel, new SearchDataRepository ());

			this.ResultsTable.DataSource = new SearchTableDataSource(this.ViewModel, this);
		}

		public override void DidReceiveMemoryWarning ()
		{		
			base.DidReceiveMemoryWarning ();		
			// Release any cached data, images, etc that aren't in use.		
		}

		partial void BtnSearch_TouchUpInside (UIButton sender)
		{
			this.Presenter.Search(this.FieldSearch.Text);
			asf
		}

		#region SearchView implementation

		public void DisplayResults ()
		{
			this.ResultsTable.ReloadData ();
		}

		#region SearchTableDataSourceListener implementation

		public void OnAddPressed (SongModel song)
		{
			Presenter.AddSongToMyList (song);
		}

		public void OnBuyPressed (SongModel song)
		{
			Presenter.PurchaseSong (song);
		}
		#endregion
		#endregion
	}
}
